# Generated by Django 3.0.6 on 2020-05-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_order_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
